### ISSUE TITLE
2.0.0 - No Data

### ISSUE THREAD

**Issue by TheChrisTech** [anclrii/Storj-Exporter#64]
My docker automatically updated to 2.0.0 last night, and resulted in no data being sent to Prometheus. Downgrading to 1.0.13 resolves the issue. @anclrii  - Please let me know if there's information I can gather for you to help troubleshoot this. I have 2 nodes that are still running 2.0.0 in case.

**Comment by anclrii** [comment]
Weird, I'm not seeing this with my nodes. 
If you can share `docker logs storj-exporter` that might help.
It may be a platform issue, I only test on `amd64`, what hardware are you running on?

**Comment by blaatblaat** [comment]
Yup, same here.
All 84 nodes logging to Prometheus anymore.
81x amd64 image and ARMv7...
Previously versions worked good... since 2.x the whole exporting is crippled...

Please roll-back the 2.x release and start this 2x release in beta

docker logs storj-exporter => No logging available...

Output of CURL from Storj-Exporter;

# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 310.0
python_gc_objects_collected_total{generation="1"} 50.0
python_gc_objects_collected_total{generation="2"} 0.0
# HELP python_gc_objects_uncollectable_total Uncollectable object found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 55.0
python_gc_collections_total{generation="1"} 5.0
python_gc_collections_total{generation="2"} 0.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="7",patchlevel="10",version="3.7.10"} 1.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 2.6279936e+07
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.6728064e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.65504160761e+09
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 20.86
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 7.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP storj_node_info Storj node info
# TYPE storj_node_info gauge
storj_node_info{nodeID="125ujm4jBTND7F9WPQbUkAES3UY4f77ntR3jfnDaC2jJNkYsTxy",type="nodeID"} 1.0
storj_node_info{type="wallet",wallet="0xF993b7A9e7a80d3D4f54c8f996Fb247D416313C0"} 1.0
storj_node_info{type="upToDate",upToDate="True"} 1.0
storj_node_info{type="version",version="1.55.1"} 1.0
storj_node_info{allowedVersion="1.24.0",type="allowedVersion"} 1.0
# HELP storj_total_diskspace Storj total diskspace metrics
# TYPE storj_total_diskspace gauge
storj_total_diskspace{type="used"} 7.79871526784e+012
storj_total_diskspace{type="available"} 7.8e+012
storj_total_diskspace{type="trash"} 7.9705973e+08
# HELP storj_total_bandwidth Storj total bandwidth metrics
# TYPE storj_total_bandwidth gauge
storj_total_bandwidth{type="used"} 4.52703394048e+011
storj_total_bandwidth{type="available"} 0.0
# HELP storj_payout_currentMonth Storj estimated payouts for current month
# TYPE storj_payout_currentMonth gauge
storj_payout_currentMonth{type="egressBandwidth"} 2.25931396352e+011
storj_payout_currentMonth{type="egressBandwidthPayout"} 451.87000000000006
storj_payout_currentMonth{type="egressRepairAudit"} 2.25748691968e+011
storj_payout_currentMonth{type="egressRepairAuditPayout"} 225.75000000000003
storj_payout_currentMonth{type="diskSpace"} 2.9974745710547886e+012
storj_payout_currentMonth{type="diskSpacePayout"} 449.63
storj_payout_currentMonth{type="heldRate"} 0.0
storj_payout_currentMonth{type="payout"} 1127.25
storj_payout_currentMonth{type="held"} 0.0
# HELP storj_sat_summary Storj satellite summary metrics
# TYPE storj_sat_summary gauge
storj_sat_summary{satellite="12tRQrMTWUWwzwGh18i7Fqs67kmdhH9t6aToeiwbo5mfS2rUmo",type="storageSummary",url="us2.storj.io:7777"} 1.2765468364704626e+012
storj_sat_summary{satellite="12tRQrMTWUWwzwGh18i7Fqs67kmdhH9t6aToeiwbo5mfS2rUmo",type="bandwidthSummary",url="us2.storj.io:7777"} 4.946304e+07
storj_sat_summary{satellite="12tRQrMTWUWwzwGh18i7Fqs67kmdhH9t6aToeiwbo5mfS2rUmo",type="egressSummary",url="us2.storj.io:7777"} 4.8354816e+07
storj_sat_summary{satellite="12tRQrMTWUWwzwGh18i7Fqs67kmdhH9t6aToeiwbo5mfS2rUmo",type="ingressSummary",url="us2.storj.io:7777"} 1.108224e+06
storj_sat_summary{satellite="12tRQrMTWUWwzwGh18i7Fqs67kmdhH9t6aToeiwbo5mfS2rUmo",type="currentStorageUsed",url="us2.storj.io:7777"} 4.645737984e+09
storj_sat_summary{satellite="12tRQrMTWUWwzwGh18i7Fqs67kmdhH9t6aToeiwbo5mfS2rUmo",type="disqualified",url="us2.storj.io:7777"} 0.0
storj_sat_summary{satellite="12tRQrMTWUWwzwGh18i7Fqs67kmdhH9t6aToeiwbo5mfS2rUmo",type="suspended",url="us2.storj.io:7777"} 0.0
storj_sat_summary{satellite="1wFTAgs9DP5RSnCqKV1eLf6N9wtk4EAtmN5DpSxcs8EjT69tGE",type="storageSummary",url="saltlake.tardigrade.io:7777"} 8.434852053487951e+014
storj_sat_summary{satellite="1wFTAgs9DP5RSnCqKV1eLf6N9wtk4EAtmN5DpSxcs8EjT69tGE",type="bandwidthSummary",url="saltlake.tardigrade.io:7777"} 3.61335393536e+011
storj_sat_summary{satellite="1wFTAgs9DP5RSnCqKV1eLf6N9wtk4EAtmN5DpSxcs8EjT69tGE",type="egressSummary",url="saltlake.tardigrade.io:7777"} 3.61165812224e+011
storj_sat_summary{satellite="1wFTAgs9DP5RSnCqKV1eLf6N9wtk4EAtmN5DpSxcs8EjT69tGE",type="ingressSummary",url="saltlake.tardigrade.io:7777"} 1.69581312e+08
storj_sat_summary{satellite="1wFTAgs9DP5RSnCqKV1eLf6N9wtk4EAtmN5DpSxcs8EjT69tGE",type="currentStorageUsed",url="saltlake.tardigrade.io:7777"} 3.084116110848e+012
storj_sat_summary{satellite="1wFTAgs9DP5RSnCqKV1eLf6N9wtk4EAtmN5DpSxcs8EjT69tGE",type="disqualified",url="saltlake.tardigrade.io:7777"} 0.0
storj_sat_summary{satellite="1wFTAgs9DP5RSnCqKV1eLf6N9wtk4EAtmN5DpSxcs8EjT69tGE",type="suspended",url="saltlake.tardigrade.io:7777"} 0.0
storj_sat_summary{satellite="121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6",type="storageSummary",url="ap1.storj.io:7777"} 8.863628319150284e+013
storj_sat_summary{satellite="121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6",type="bandwidthSummary",url="ap1.storj.io:7777"} 3.645127936e+09
storj_sat_summary{satellite="121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6",type="egressSummary",url="ap1.storj.io:7777"} 3.55561344e+09
storj_sat_summary{satellite="121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6",type="ingressSummary",url="ap1.storj.io:7777"} 8.9514496e+07
storj_sat_summary{satellite="121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6",type="currentStorageUsed",url="ap1.storj.io:7777"} 3.2267789056e+011
storj_sat_summary{satellite="121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6",type="disqualified",url="ap1.storj.io:7777"} 0.0
storj_sat_summary{satellite="121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6",type="suspended",url="ap1.storj.io:7777"} 0.0
storj_sat_summary{satellite="12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S",type="storageSummary",url="us1.storj.io:7777"} 5.9457992429901445e+013
storj_sat_summary{satellite="12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S",type="bandwidthSummary",url="us1.storj.io:7777"} 3.555030528e+09
storj_sat_summary{satellite="12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S",type="egressSummary",url="us1.storj.io:7777"} 3.1737984e+09
storj_sat_summary{satellite="12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S",type="ingressSummary",url="us1.storj.io:7777"} 3.81232128e+08
storj_sat_summary{satellite="12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S",type="currentStorageUsed",url="us1.storj.io:7777"} 2.17069880064e+011
storj_sat_summary{satellite="12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S",type="disqualified",url="us1.storj.io:7777"} 0.0
storj_sat_summary{satellite="12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S",type="suspended",url="us1.storj.io:7777"} 0.0
storj_sat_summary{satellite="12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs",type="storageSummary",url="eu1.storj.io:7777"} 1.7766261319776325e+014
storj_sat_summary{satellite="12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs",type="bandwidthSummary",url="eu1.storj.io:7777"} 9.151806208e+09
storj_sat_summary{satellite="12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs",type="egressSummary",url="eu1.storj.io:7777"} 8.895141888e+09
storj_sat_summary{satellite="12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs",type="ingressSummary",url="eu1.storj.io:7777"} 2.5666432e+08
storj_sat_summary{satellite="12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs",type="currentStorageUsed",url="eu1.storj.io:7777"} 6.93955253504e+011
storj_sat_summary{satellite="12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs",type="disqualified",url="eu1.storj.io:7777"} 0.0
storj_sat_summary{satellite="12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs",type="suspended",url="eu1.storj.io:7777"} 0.0
storj_sat_summary{satellite="12rfG3sh9NCWiX3ivPjq2HtdLmbqCrvHVEzJubnzFzosMuawymB",type="storageSummary",url="europe-north-1.tardigrade.io:7777"} 9.876630501550146e+014
storj_sat_summary{satellite="12rfG3sh9NCWiX3ivPjq2HtdLmbqCrvHVEzJubnzFzosMuawymB",type="bandwidthSummary",url="europe-north-1.tardigrade.io:7777"} 7.49665728e+010
storj_sat_summary{satellite="12rfG3sh9NCWiX3ivPjq2HtdLmbqCrvHVEzJubnzFzosMuawymB",type="egressSummary",url="europe-north-1.tardigrade.io:7777"} 7.4841367552e+010
storj_sat_summary{satellite="12rfG3sh9NCWiX3ivPjq2HtdLmbqCrvHVEzJubnzFzosMuawymB",type="ingressSummary",url="europe-north-1.tardigrade.io:7777"} 1.25205248e+08
storj_sat_summary{satellite="12rfG3sh9NCWiX3ivPjq2HtdLmbqCrvHVEzJubnzFzosMuawymB",type="currentStorageUsed",url="europe-north-1.tardigrade.io:7777"} 3.473084590848e+012
storj_sat_summary{satellite="12rfG3sh9NCWiX3ivPjq2HtdLmbqCrvHVEzJubnzFzosMuawymB",type="disqualified",url="europe-north-1.tardigrade.io:7777"} 0.0
storj_sat_summary{satellite="12rfG3sh9NCWiX3ivPjq2HtdLmbqCrvHVEzJubnzFzosMuawymB",type="suspended",url="europe-north-1.tardigrade.io:7777"} 0.0
# HELP storj_sat_audit Storj satellite audit metrics
# TYPE storj_sat_audit gauge
storj_sat_audit{satellite="12tRQrMTWUWwzwGh18i7Fqs67kmdhH9t6aToeiwbo5mfS2rUmo",type="auditScore",url="us2.storj.io:7777"} 1.0
storj_sat_audit{satellite="12tRQrMTWUWwzwGh18i7Fqs67kmdhH9t6aToeiwbo5mfS2rUmo",type="suspensionScore",url="us2.storj.io:7777"} 1.0
storj_sat_audit{satellite="12tRQrMTWUWwzwGh18i7Fqs67kmdhH9t6aToeiwbo5mfS2rUmo",type="onlineScore",url="us2.storj.io:7777"} 0.9991666666666668
storj_sat_audit{satellite="1wFTAgs9DP5RSnCqKV1eLf6N9wtk4EAtmN5DpSxcs8EjT69tGE",type="auditScore",url="saltlake.tardigrade.io:7777"} 1.0
storj_sat_audit{satellite="1wFTAgs9DP5RSnCqKV1eLf6N9wtk4EAtmN5DpSxcs8EjT69tGE",type="suspensionScore",url="saltlake.tardigrade.io:7777"} 1.0
storj_sat_audit{satellite="1wFTAgs9DP5RSnCqKV1eLf6N9wtk4EAtmN5DpSxcs8EjT69tGE",type="onlineScore",url="saltlake.tardigrade.io:7777"} 0.9995177611451462
storj_sat_audit{satellite="121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6",type="auditScore",url="ap1.storj.io:7777"} 1.0
storj_sat_audit{satellite="121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6",type="suspensionScore",url="ap1.storj.io:7777"} 1.0
storj_sat_audit{satellite="121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6",type="onlineScore",url="ap1.storj.io:7777"} 0.9994972680038896
storj_sat_audit{satellite="12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S",type="auditScore",url="us1.storj.io:7777"} 1.0
storj_sat_audit{satellite="12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S",type="suspensionScore",url="us1.storj.io:7777"} 1.0
storj_sat_audit{satellite="12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S",type="onlineScore",url="us1.storj.io:7777"} 0.9999431171786121
storj_sat_audit{satellite="12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs",type="auditScore",url="eu1.storj.io:7777"} 1.0
storj_sat_audit{satellite="12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs",type="suspensionScore",url="eu1.storj.io:7777"} 1.0
storj_sat_audit{satellite="12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs",type="onlineScore",url="eu1.storj.io:7777"} 0.9993950359465148
storj_sat_audit{satellite="12rfG3sh9NCWiX3ivPjq2HtdLmbqCrvHVEzJubnzFzosMuawymB",type="auditScore",url="europe-north-1.tardigrade.io:7777"} 1.0
storj_sat_audit{satellite="12rfG3sh9NCWiX3ivPjq2HtdLmbqCrvHVEzJubnzFzosMuawymB",type="suspensionScore",url="europe-north-1.tardigrade.io:7777"} 1.0
storj_sat_audit{satellite="12rfG3sh9NCWiX3ivPjq2HtdLmbqCrvHVEzJubnzFzosMuawymB",type="onlineScore",url="europe-north-1.tardigrade.io:7777"} 0.999524450593214
# HELP storj_sat_month_egress Storj satellite egress since current month start
# TYPE storj_sat_month_egress gauge
storj_sat_month_egress{satellite="12tRQrMTWUWwzwGh18i7Fqs67kmdhH9t6aToeiwbo5mfS2rUmo",type="repair",url="us2.storj.io:7777"} 4.792064e+07
storj_sat_month_egress{satellite="12tRQrMTWUWwzwGh18i7Fqs67kmdhH9t6aToeiwbo5mfS2rUmo",type="audit",url="us2.storj.io:7777"} 79872.0
storj_sat_month_egress{satellite="12tRQrMTWUWwzwGh18i7Fqs67kmdhH9t6aToeiwbo5mfS2rUmo",type="usage",url="us2.storj.io:7777"} 354304.0
storj_sat_month_egress{satellite="1wFTAgs9DP5RSnCqKV1eLf6N9wtk4EAtmN5DpSxcs8EjT69tGE",type="repair",url="saltlake.tardigrade.io:7777"} 1.3633098752e+011
storj_sat_month_egress{satellite="1wFTAgs9DP5RSnCqKV1eLf6N9wtk4EAtmN5DpSxcs8EjT69tGE",type="audit",url="saltlake.tardigrade.io:7777"} 493568.0
storj_sat_month_egress{satellite="1wFTAgs9DP5RSnCqKV1eLf6N9wtk4EAtmN5DpSxcs8EjT69tGE",type="usage",url="saltlake.tardigrade.io:7777"} 2.24834331136e+011
storj_sat_month_egress{satellite="121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6",type="repair",url="ap1.storj.io:7777"} 3.521508352e+09
storj_sat_month_egress{satellite="121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6",type="audit",url="ap1.storj.io:7777"} 132608.0
storj_sat_month_egress{satellite="121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6",type="usage",url="ap1.storj.io:7777"} 3.397248e+07
storj_sat_month_egress{satellite="12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S",type="repair",url="us1.storj.io:7777"} 2.440947456e+09
storj_sat_month_egress{satellite="12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S",type="audit",url="us1.storj.io:7777"} 60928.0
storj_sat_month_egress{satellite="12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S",type="usage",url="us1.storj.io:7777"} 7.32790016e+08
storj_sat_month_egress{satellite="12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs",type="repair",url="eu1.storj.io:7777"} 8.565337856e+09
storj_sat_month_egress{satellite="12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs",type="audit",url="eu1.storj.io:7777"} 209920.0
storj_sat_month_egress{satellite="12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs",type="usage",url="eu1.storj.io:7777"} 3.29594112e+08
storj_sat_month_egress{satellite="12rfG3sh9NCWiX3ivPjq2HtdLmbqCrvHVEzJubnzFzosMuawymB",type="repair",url="europe-north-1.tardigrade.io:7777"} 7.4840452608e+010
storj_sat_month_egress{satellite="12rfG3sh9NCWiX3ivPjq2HtdLmbqCrvHVEzJubnzFzosMuawymB",type="audit",url="europe-north-1.tardigrade.io:7777"} 560640.0
storj_sat_month_egress{satellite="12rfG3sh9NCWiX3ivPjq2HtdLmbqCrvHVEzJubnzFzosMuawymB",type="usage",url="europe-north-1.tardigrade.io:7777"} 354304.0
# HELP storj_sat_month_ingress Storj satellite ingress since current month start
# TYPE storj_sat_month_ingress gauge
storj_sat_month_ingress{satellite="12tRQrMTWUWwzwGh18i7Fqs67kmdhH9t6aToeiwbo5mfS2rUmo",type="repair",url="us2.storj.io:7777"} 399104.0
storj_sat_month_ingress{satellite="12tRQrMTWUWwzwGh18i7Fqs67kmdhH9t6aToeiwbo5mfS2rUmo",type="usage",url="us2.storj.io:7777"} 709120.0
storj_sat_month_ingress{satellite="1wFTAgs9DP5RSnCqKV1eLf6N9wtk4EAtmN5DpSxcs8EjT69tGE",type="repair",url="saltlake.tardigrade.io:7777"} 1.69581312e+08
storj_sat_month_ingress{satellite="1wFTAgs9DP5RSnCqKV1eLf6N9wtk4EAtmN5DpSxcs8EjT69tGE",type="usage",url="saltlake.tardigrade.io:7777"} 0.0
storj_sat_month_ingress{satellite="121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6",type="repair",url="ap1.storj.io:7777"} 1.354624e+07
storj_sat_month_ingress{satellite="121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6",type="usage",url="ap1.storj.io:7777"} 7.5968256e+07
storj_sat_month_ingress{satellite="12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S",type="repair",url="us1.storj.io:7777"} 1.5021568e+07
storj_sat_month_ingress{satellite="12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S",type="usage",url="us1.storj.io:7777"} 3.6621056e+08
storj_sat_month_ingress{satellite="12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs",type="repair",url="eu1.storj.io:7777"} 2.1868544e+07
storj_sat_month_ingress{satellite="12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs",type="usage",url="eu1.storj.io:7777"} 2.34795776e+08
storj_sat_month_ingress{satellite="12rfG3sh9NCWiX3ivPjq2HtdLmbqCrvHVEzJubnzFzosMuawymB",type="repair",url="europe-north-1.tardigrade.io:7777"} 1.24850688e+08
storj_sat_month_ingress{satellite="12rfG3sh9NCWiX3ivPjq2HtdLmbqCrvHVEzJubnzFzosMuawymB",type="usage",url="europe-north-1.tardigrade.io:7777"} 354560.0
# HELP storj_sat_day_storage Storj satellite data stored on disk since current day start
# TYPE storj_sat_day_storage gauge
storj_sat_day_storage{satellite="12tRQrMTWUWwzwGh18i7Fqs67kmdhH9t6aToeiwbo5mfS2rUmo",type="atRestTotal",url="us2.storj.io:7777"} 5.1010513720519066e+010
storj_sat_day_storage{satellite="1wFTAgs9DP5RSnCqKV1eLf6N9wtk4EAtmN5DpSxcs8EjT69tGE",type="atRestTotal",url="saltlake.tardigrade.io:7777"} 3.3664248025098684e+013
storj_sat_day_storage{satellite="121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6",type="atRestTotal",url="ap1.storj.io:7777"} 4.404924503608421e+012
storj_sat_day_storage{satellite="12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S",type="atRestTotal",url="us1.storj.io:7777"} 2.9969945815985566e+012
storj_sat_day_storage{satellite="12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs",type="atRestTotal",url="eu1.storj.io:7777"} 0.0
storj_sat_day_storage{satellite="12rfG3sh9NCWiX3ivPjq2HtdLmbqCrvHVEzJubnzFzosMuawymB",type="atRestTotal",url="europe-north-1.tardigrade.io:7777"} 4.577967483433713e+013

**Comment by anclrii** [comment]
Can you try if this one works https://github.com/anclrii/Storj-Exporter-dashboard/blob/master/Storj-Exporter-Boom-Table.json?

There were some deprecated metrics removed in favour of labels in v2 and https://grafana.com/grafana/dashboards/13896 is probably still using the old ones. We can ask @kevinkk525 to update Storj-Exporter-Boom-Table-combined.

**Comment by kevinkk525** [comment]
Sadly can't update due to illness. Feel free to change

**Comment by anclrii** [comment]
@kevinkk525 hope you get better soon!

I'll look to update the combined dashboard when I get some time. Created https://github.com/anclrii/Storj-Exporter-dashboard/issues/22.

**Comment by blaatblaat** [comment]
> Can you try if this one works https://github.com/anclrii/Storj-Exporter-dashboard/blob/master/Storj-Exporter-Boom-Table.json?
> 
> There were some deprecated metrics removed in favour of labels in v2 and https://grafana.com/grafana/dashboards/13896 is probably still using the old ones. We can ask @kevinkk525 to update Storj-Exporter-Boom-Table-combined.

Nope, that one is completly broken...
=>
Templating [node]
Error updating options: e.replace is not a function

**Comment by TheChrisTech** [comment]
I'm running Grafana `v8.5.5`.
Looking through Prometheus, it seems that a bunch of metrics were depreciated in 2.0, which my dashboards were reliant upon, such as `lastPinged_info`, conversion of `storj_nodeID_info` to `storj_node_info`, and some other enhancements. I had alerts set up on some of these metrics, and they paged out as soon as the docker updated.

I understand development can make product changes like this, but it would be nice to know what exactly changed (or have some sort of migration documentation for variable to variable).

For now, I've gotten my dashboard up and working, (and confirmed that the .json file provided in 2.x does work too), but I'm not searching for a solution for the removal of `lastPinged_info`. Essentially, I chart out how many nodes have checked in, and if the number drops below [My Node Count] for 5 minutes, send me a text message. Any ideas?

**Comment by blaatblaat** [comment]
> @blaatblaat What version of grafana are you using? It works fine on `v8.5.5`.

Mate, this whole thing isn't working...
Just updated the whole thing to v8.5.5 (d32ae18909) with the latest yesoreyeram-boomtable-panel version: 1.4.1

This thing just doesn't work :-/

**Comment by anclrii** [comment]
@TheChrisTech yeah not sure how to communicate deprecating metrics better. I kept them until next major release for a while. 

The change is that metrics like storj_[type]_info are now under a single `storj_node_info` with type being a label.

Also removal of `lastPinged` metric was specifically requested in https://github.com/anclrii/Storj-Exporter/issues/56.

> how many nodes have checked in

I'm not sure what this means but it sounds like you could just use something like `count(storj_node_info{type="nodeID"})` to get count for live nodes. Did you rely on values in lastPinged? If you need the values I can bring it back.

**Comment by blaatblaat** [comment]
Sir!

We're back on track!
Seems indeed that the Grafana update solved most issues.
Reworking the dashboard right now, but it seems that the Storj-Exporter is working again.
Thx for pointing out to update Grafana (Y)

**Comment by anclrii** [comment]
@blaatblaat I'm glad it works.

If you are updating https://github.com/anclrii/Storj-Exporter-dashboard/blob/527f9946e625dad9ba0864e90b5a05a2f296145b/alternatives/dashboard_exporter_combined.json dashboard would be great if you can raise a PR.

**Comment by m0useP4d** [comment]
> 

@anclrii 
I still have storj_sat_day_ingress and storj_sat_day_egress in use in my dashboard. Well after updating the container I have now noticed that they have also been removed. 
How can I retrieve them in the new version or can we please get it back?
